apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AnalysisRun
  metadata:
    annotations:
      rollout.argoproj.io/revision: "2"
    creationTimestamp: "2026-06-21T00:16:03Z"
    generation: 12
    labels:
      app: tcc-api
      rollout-type: PrePromotion
      rollouts-pod-template-hash: 776d9bb8df
    name: tcc-api-bluegreen-776d9bb8df-2-pre
    namespace: app-tcc
    ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Rollout
      name: tcc-api-bluegreen
      uid: 4d2667d5-e5d7-4e67-adf6-20c48933333b
    resourceVersion: "9895864"
    uid: ef2805af-636a-4fd9-a6c1-300f1669807c
  spec:
    metrics:
    - count: 5
      failureCondition: result[0] < 0.90
      failureLimit: 2
      interval: 30s
      name: success-rate
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            sum(rate(http_requests_total{path!="/metrics",status=~"2.."}[1m]))
            /
            sum(rate(http_requests_total{path!="/metrics"}[1m]))
      successCondition: result[0] >= 0.95
    - count: 5
      failureCondition: result[0] > 2000
      failureLimit: 2
      interval: 30s
      name: latency-p95
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_ms_bucket{path!="/metrics"}[1m]))
              by (le)
            )
      successCondition: result[0] <= 1000
    - count: 5
      failureCondition: result[0] > 0.10
      failureLimit: 2
      interval: 30s
      name: error-rate
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            sum(rate(app_errors_total[1m]))
      successCondition: result[0] <= 0.05
  status:
    completedAt: "2026-06-21T00:18:13Z"
    dryRunSummary: {}
    message: Metric "error-rate" assessed Failed due to failed (3) > failureLimit
      (2)
    metricResults:
    - count: 4
      error: 4
      failed: 3
      measurements:
      - finishedAt: "2026-06-21T00:16:03Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:16:03Z"
      - finishedAt: "2026-06-21T00:16:13Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:16:13Z"
      - finishedAt: "2026-06-21T00:16:23Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:16:23Z"
      - finishedAt: "2026-06-21T00:16:33Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:16:33Z"
      - finishedAt: "2026-06-21T00:16:43Z"
        phase: Successful
        startedAt: "2026-06-21T00:16:43Z"
        value: '[0]'
      - finishedAt: "2026-06-21T00:17:13Z"
        phase: Failed
        startedAt: "2026-06-21T00:17:13Z"
        value: '[0.13988853425368813]'
      - finishedAt: "2026-06-21T00:17:43Z"
        phase: Failed
        startedAt: "2026-06-21T00:17:43Z"
        value: '[0.31206262347774016]'
      - finishedAt: "2026-06-21T00:18:13Z"
        phase: Failed
        startedAt: "2026-06-21T00:18:13Z"
        value: '[1.1750032074337602]'
      metadata:
        ResolvedPrometheusQuery: |
          sum(rate(app_errors_total[1m]))
      name: error-rate
      phase: Failed
      successful: 1
    - consecutiveSuccess: 5
      count: 5
      measurements:
      - finishedAt: "2026-06-21T00:16:03Z"
        phase: Successful
        startedAt: "2026-06-21T00:16:03Z"
        value: '[1]'
      - finishedAt: "2026-06-21T00:16:33Z"
        phase: Successful
        startedAt: "2026-06-21T00:16:33Z"
        value: '[1]'
      - finishedAt: "2026-06-21T00:17:03Z"
        phase: Successful
        startedAt: "2026-06-21T00:17:03Z"
        value: '[0.9988161089547518]'
      - finishedAt: "2026-06-21T00:17:33Z"
        phase: Successful
        startedAt: "2026-06-21T00:17:33Z"
        value: '[0.9982217800640408]'
      - finishedAt: "2026-06-21T00:18:03Z"
        phase: Successful
        startedAt: "2026-06-21T00:18:03Z"
        value: '[0.9962762053404632]'
      metadata:
        ResolvedPrometheusQuery: |
          sum(rate(http_requests_total{path!="/metrics",status=~"2.."}[1m]))
          /
          sum(rate(http_requests_total{path!="/metrics"}[1m]))
      name: success-rate
      phase: Successful
      successful: 5
    - consecutiveSuccess: 5
      count: 5
      measurements:
      - finishedAt: "2026-06-21T00:16:03Z"
        phase: Successful
        startedAt: "2026-06-21T00:16:03Z"
        value: '[9.799324781650302]'
      - finishedAt: "2026-06-21T00:16:33Z"
        phase: Successful
        startedAt: "2026-06-21T00:16:33Z"
        value: '[32.50507445197083]'
      - finishedAt: "2026-06-21T00:17:03Z"
        phase: Successful
        startedAt: "2026-06-21T00:17:03Z"
        value: '[848.077367818928]'
      - finishedAt: "2026-06-21T00:17:33Z"
        phase: Successful
        startedAt: "2026-06-21T00:17:33Z"
        value: '[856.6926606044402]'
      - finishedAt: "2026-06-21T00:18:03Z"
        phase: Successful
        startedAt: "2026-06-21T00:18:03Z"
        value: '[864.0680126901217]'
      metadata:
        ResolvedPrometheusQuery: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_ms_bucket{path!="/metrics"}[1m]))
            by (le)
          )
      name: latency-p95
      phase: Successful
      successful: 5
    phase: Failed
    runSummary:
      count: 3
      failed: 1
      successful: 2
    startedAt: "2026-06-21T00:16:03Z"
- apiVersion: argoproj.io/v1alpha1
  kind: AnalysisRun
  metadata:
    annotations:
      rollout.argoproj.io/revision: "6"
    creationTimestamp: "2026-06-21T00:08:56Z"
    generation: 7
    labels:
      app: tcc-api
      rollout-type: Step
      rollouts-pod-template-hash: 776d9bb8df
      step-index: "2"
    name: tcc-api-canary-776d9bb8df-6-2
    namespace: app-tcc
    ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Rollout
      name: tcc-api-canary
      uid: d9e1b49e-89d3-42e8-a20f-50e9d85abcc4
    resourceVersion: "9894968"
    uid: 1181640d-7979-4105-bfd6-07108627a805
  spec:
    metrics:
    - count: 5
      failureCondition: result[0] < 0.90
      failureLimit: 2
      interval: 30s
      name: success-rate
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            sum(rate(http_requests_total{path!="/metrics",status=~"2.."}[1m]))
            /
            sum(rate(http_requests_total{path!="/metrics"}[1m]))
      successCondition: result[0] >= 0.95
    - count: 5
      failureCondition: result[0] > 2000
      failureLimit: 2
      interval: 30s
      name: latency-p95
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_ms_bucket{path!="/metrics"}[1m]))
              by (le)
            )
      successCondition: result[0] <= 1000
    - count: 5
      failureCondition: result[0] > 0.10
      failureLimit: 2
      interval: 30s
      name: error-rate
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            sum(rate(app_errors_total[1m]))
      successCondition: result[0] <= 0.05
  status:
    completedAt: "2026-06-21T00:09:36Z"
    dryRunSummary: {}
    message: 'Metric "error-rate" assessed Error due to consecutiveErrors (5) > consecutiveErrorLimit
      (4): "Error Message: reflect: slice index out of range"'
    metricResults:
    - consecutiveError: 5
      error: 5
      measurements:
      - finishedAt: "2026-06-21T00:08:56Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:08:56Z"
      - finishedAt: "2026-06-21T00:09:06Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:09:06Z"
      - finishedAt: "2026-06-21T00:09:16Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:09:16Z"
      - finishedAt: "2026-06-21T00:09:26Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:09:26Z"
      - finishedAt: "2026-06-21T00:09:36Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-21T00:09:36Z"
      message: 'reflect: slice index out of range'
      metadata:
        ResolvedPrometheusQuery: |
          sum(rate(app_errors_total[1m]))
      name: error-rate
      phase: Error
    - consecutiveSuccess: 2
      count: 2
      measurements:
      - finishedAt: "2026-06-21T00:08:56Z"
        phase: Successful
        startedAt: "2026-06-21T00:08:56Z"
        value: '[1]'
      - finishedAt: "2026-06-21T00:09:26Z"
        phase: Successful
        startedAt: "2026-06-21T00:09:26Z"
        value: '[1]'
      metadata:
        ResolvedPrometheusQuery: |
          sum(rate(http_requests_total{path!="/metrics",status=~"2.."}[1m]))
          /
          sum(rate(http_requests_total{path!="/metrics"}[1m]))
      name: success-rate
      phase: Successful
      successful: 2
    - consecutiveSuccess: 2
      count: 2
      measurements:
      - finishedAt: "2026-06-21T00:08:56Z"
        phase: Successful
        startedAt: "2026-06-21T00:08:56Z"
        value: '[590.2252810591976]'
      - finishedAt: "2026-06-21T00:09:26Z"
        phase: Successful
        startedAt: "2026-06-21T00:09:26Z"
        value: '[546.196577592292]'
      metadata:
        ResolvedPrometheusQuery: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_ms_bucket{path!="/metrics"}[1m]))
            by (le)
          )
      name: latency-p95
      phase: Successful
      successful: 2
    phase: Error
    runSummary:
      count: 3
      error: 1
      successful: 2
    startedAt: "2026-06-21T00:08:56Z"
- apiVersion: argoproj.io/v1alpha1
  kind: AnalysisRun
  metadata:
    annotations:
      rollout.argoproj.io/revision: "8"
    creationTimestamp: "2026-06-22T20:55:37Z"
    generation: 3
    labels:
      app: tcc-api
      rollout-type: Step
      rollouts-pod-template-hash: 787bdcb856
      step-index: "2"
    name: tcc-api-canary-787bdcb856-8-2
    namespace: app-tcc
    ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Rollout
      name: tcc-api-canary
      uid: d9e1b49e-89d3-42e8-a20f-50e9d85abcc4
    resourceVersion: "10106749"
    uid: a176c4c3-1e5b-4f62-af7f-f5d12084db16
  spec:
    metrics:
    - count: 5
      failureCondition: result[0] < 0.90
      failureLimit: 2
      interval: 30s
      name: success-rate
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            sum(rate(http_requests_total{path!="/metrics",status=~"2.."}[1m]))
            /
            sum(rate(http_requests_total{path!="/metrics"}[1m]))
      successCondition: result[0] >= 0.95
    - count: 5
      failureCondition: result[0] > 2000
      failureLimit: 2
      interval: 30s
      name: latency-p95
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_ms_bucket{path!="/metrics"}[1m]))
              by (le)
            )
      successCondition: result[0] <= 1000
    - count: 5
      failureCondition: result[0] > 0.10
      failureLimit: 2
      interval: 30s
      name: error-rate
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          authentication:
            oauth2: {}
            sigv4: {}
          query: |
            sum(rate(app_errors_total[1m]))
      successCondition: result[0] <= 0.05
  status:
    dryRunSummary: {}
    metricResults:
    - consecutiveError: 2
      error: 2
      measurements:
      - finishedAt: "2026-06-22T20:55:37Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-22T20:55:37Z"
      - finishedAt: "2026-06-22T20:55:47Z"
        message: 'reflect: slice index out of range'
        phase: Error
        startedAt: "2026-06-22T20:55:47Z"
      metadata:
        ResolvedPrometheusQuery: |
          sum(rate(app_errors_total[1m]))
      name: error-rate
      phase: Running
    - consecutiveSuccess: 1
      count: 1
      measurements:
      - finishedAt: "2026-06-22T20:55:37Z"
        phase: Successful
        startedAt: "2026-06-22T20:55:37Z"
        value: '[1]'
      metadata:
        ResolvedPrometheusQuery: |
          sum(rate(http_requests_total{path!="/metrics",status=~"2.."}[1m]))
          /
          sum(rate(http_requests_total{path!="/metrics"}[1m]))
      name: success-rate
      phase: Running
      successful: 1
    - consecutiveSuccess: 1
      count: 1
      measurements:
      - finishedAt: "2026-06-22T20:55:37Z"
        phase: Successful
        startedAt: "2026-06-22T20:55:37Z"
        value: '[9.878043691701013]'
      metadata:
        ResolvedPrometheusQuery: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_ms_bucket{path!="/metrics"}[1m]))
            by (le)
          )
      name: latency-p95
      phase: Running
      successful: 1
    phase: Running
    runSummary:
      count: 3
    startedAt: "2026-06-22T20:55:37Z"
kind: List
metadata:
  resourceVersion: ""
