apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: tcc-rollouts:argoproj.io/Rollout:app-tcc/tcc-api-canary
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"tcc-rollouts:argoproj.io/Rollout:app-tcc/tcc-api-canary"},"name":"tcc-api-canary","namespace":"app-tcc"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"tcc-api"}},"strategy":{"canary":{"steps":[{"setWeight":20},{"pause":{"duration":"30s"}},{"analysis":{"templates":[{"templateName":"tcc-api-success-rate"}]}},{"setWeight":50},{"pause":{"duration":"30s"}},{"setWeight":100}]}},"template":{"metadata":{"labels":{"app":"tcc-api"}},"spec":{"containers":[{"env":[{"name":"APP_VERSION","value":"v2.0.0"},{"name":"APP_COLOR","value":"green"},{"name":"ERROR_RATE","value":"0.05"},{"name":"SLOW_MS","value":"800"}],"image":"gabrieldores/tcc-api:v1","livenessProbe":{"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":10,"periodSeconds":15},"name":"tcc-api","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/ready","port":3000},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"200m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"64Mi"}}}]}}}}
    rollout.argoproj.io/revision: "8"
  creationTimestamp: "2026-06-16T00:42:11Z"
  generation: 9
  name: tcc-api-canary
  namespace: app-tcc
  resourceVersion: "10106737"
  uid: d9e1b49e-89d3-42e8-a20f-50e9d85abcc4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tcc-api
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: tcc-api-success-rate
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: tcc-api
    spec:
      containers:
      - env:
        - name: APP_VERSION
          value: v2.0.0
        - name: APP_COLOR
          value: green
        - name: ERROR_RATE
          value: "0.05"
        - name: SLOW_MS
          value: "800"
        image: gabrieldores/tcc-api:v1
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
        name: tcc-api
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen: {}
  canary:
    currentStepAnalysisRunStatus:
      name: tcc-api-canary-787bdcb856-8-2
      status: Running
  conditions:
  - lastTransitionTime: "2026-06-21T00:16:33Z"
    lastUpdateTime: "2026-06-21T00:16:33Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-22T20:54:50Z"
    lastUpdateTime: "2026-06-22T20:54:50Z"
    message: Rollout is not healthy
    reason: RolloutHealthy
    status: "False"
    type: Healthy
  - lastTransitionTime: "2026-06-22T20:54:50Z"
    lastUpdateTime: "2026-06-22T20:54:50Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "False"
    type: Completed
  - lastTransitionTime: "2026-06-22T20:55:36Z"
    lastUpdateTime: "2026-06-22T20:55:36Z"
    message: ReplicaSet "tcc-api-canary-787bdcb856" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-06-22T20:55:36Z"
    lastUpdateTime: "2026-06-22T20:55:36Z"
    message: Rollout is paused
    reason: RolloutPaused
    status: "False"
    type: Paused
  currentPodHash: 787bdcb856
  currentStepHash: 799df774d7
  currentStepIndex: 2
  message: more replicas need to be updated
  observedGeneration: "9"
  phase: Progressing
  readyReplicas: 5
  replicas: 5
  selector: app=tcc-api
  stableRS: 86c5dc54d7
  updatedReplicas: 1
